name: Deploy to Production

on:
  push:
    branches:
      - T2-63-bug-in-voice-patches

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to production
        run: |
          # Add your deployment commands here
          # Example: deploying to a hosting service
          # such as AWS, Heroku, or Netlify
          # Replace the placeholders with your actual commands
          echo "Deploying to production..."
          # Your deployment command 1
          # Your deployment command 2
          # ...

