name: Deploy to Production

on:
  push:
    branches:
      - T2-55-rotation-animation

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Deploy to production
        run: |
          echo "Deploying to production..."
          echo "Deployment successful!"
