name: Deploy to Production

on:
  push:
    branches:
      - T2-22-draw-system-ui

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Deploy to production
        run: |
          # Add your deployment commands here
          echo "Deploying to production..."
          echo "Deployment successful!"

